### ISSUE TITLE
[Crash] Crash on startup when trying to use OCRocketry and AdvancedRocketry 2.0.0

### ISSUE THREAD

**Issue by gatoborrachon** [slava110/OCRocketry#6]
**Describe the bug**
When you try to load the newest version of AR and OCRocketry, you will get this crash.

**To Reproduce**
1. Install AR and this Addon
2. try to launch the game
3. See error

**Expected behavior**
Crash on startup: https://pastebin.com/DheHhpF3

**Comment by slava110** [comment]
Thanks! Will be fixed today

**Comment by gatoborrachon** [comment]
ok, i see that they changed a lot of the internal bases of the mod, so take your time, many thanks for answer

**Comment by slava110** [comment]
Fixed with https://github.com/slava110/OCRocketry/commit/95d3a78a422987ac8c394f4084441997667c2d61
CF update link: https://www.curseforge.com/minecraft/mc-mods/ocrocketry/files/3268062

**Comment by gatoborrachon** [comment]
many thanks again
