### ISSUE TITLE
Crash with AR 1.7.0-237

### ISSUE THREAD

**Issue by ThePatmann** [slava110/OCRocketry#7]
**Describe the bug**
The game will crash during the startup when using the latest AR version.

**To Reproduce**
1. Install AR, OC & OCRocketry
2. Attempt to launch
3. Experience startup crash

**Expected behavior**
--OMIT--

**Screenshots**
--OMIT--

**OC program**
--OMIT--

**Additional context**
--OMIT--

**Comment by slava110** [comment]
If there is crash - provide crash log
You can find it in `crash-reports` folder

**Comment by slava110** [comment]
Nvm. You're using outdated version of AdvancedRocketry. I can add minimum version parameter so it will say `OCRocketry requires AdvRocketry 2.0.0+` instead of crashing

**Comment by ThePatmann** [comment]
Yep, didn't realize that OCRocketry required 2.0, I haven't been using Beta Versions and must've missed the move to 2.0, Thanks!
