### ISSUE TITLE
trying to put this in a modpack update for Steve's New Glaxy bud sadly wont be able to

### ISSUE THREAD

**Issue by spiro-angelakis** [slava110/OCRocketry#8]
**Describe the bug**
crashes mc on boot

**To Reproduce**
1. put mods in mods folder
2. run game
3. game break, get error

**Expected behavior**
mod work :(

**Screenshots**
crash report file attached
[crash-2021-05-19_03.16.41-client.txt](https://github.com/slava110/OCRocketry/files/6507076/crash-2021-05-19_03.16.41-client.txt)

I suppose i will have to leave this mod out of the pack for now, i would love to add it in if it gets fixed looks amazing!

**Comment by slava110** [comment]
Outdated Advanced Rocketry. Version 2.0.0 or higher required. Use previous version of OCRocketry, might work
